// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Artifact struct {
	ID              int64     `json:"id"`
	ArtifactType    string    `json:"artifact_type"`
	ArtifactName    string    `json:"artifact_name"`
	ArtifactVersion string    `json:"artifact_version"`
	CreatedAt       time.Time `json:"created_at"`
}

type Sbom struct {
	ID         int64          `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	ArtifactID int64          `json:"artifact_id"`
	Manifest   sql.NullString `json:"manifest"`
	Status     string         `json:"status"`
	JobLog     sql.NullString `json:"job_log"`
}

type Scan struct {
	ID         int64          `json:"id"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
	ArtifactID int64          `json:"artifact_id"`
	Status     string         `json:"status"`
	Report     sql.NullString `json:"report"`
	JobLog     sql.NullString `json:"job_log"`
}
