// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CountScanJobs(ctx context.Context) (int64, error)
	DeleteScanJob(ctx context.Context, id int64) error
	GetScanJobByID(ctx context.Context, id int64) (ScanJob, error)
	GetScanJobsList(ctx context.Context, arg GetScanJobsListParams) ([]ScanJob, error)
	InsertScanJob(ctx context.Context, arg InsertScanJobParams) (ScanJob, error)
	UpdateScanJob(ctx context.Context, arg UpdateScanJobParams) (ScanJob, error)
}

var _ Querier = (*Queries)(nil)
