// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: v1/scanner.proto

package scannerv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sbom string `protobuf:"bytes,1,opt,name=sbom,proto3" json:"sbom,omitempty"`
}

func (x *AddScanRequest) Reset() {
	*x = AddScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_scanner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScanRequest) ProtoMessage() {}

func (x *AddScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_scanner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScanRequest.ProtoReflect.Descriptor instead.
func (*AddScanRequest) Descriptor() ([]byte, []int) {
	return file_v1_scanner_proto_rawDescGZIP(), []int{0}
}

func (x *AddScanRequest) GetSbom() string {
	if x != nil {
		return x.Sbom
	}
	return ""
}

type AddScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReportId string `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
}

func (x *AddScanResponse) Reset() {
	*x = AddScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_scanner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScanResponse) ProtoMessage() {}

func (x *AddScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_scanner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScanResponse.ProtoReflect.Descriptor instead.
func (*AddScanResponse) Descriptor() ([]byte, []int) {
	return file_v1_scanner_proto_rawDescGZIP(), []int{1}
}

func (x *AddScanResponse) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type GetScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *GetScanRequest) Reset() {
	*x = GetScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_scanner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanRequest) ProtoMessage() {}

func (x *GetScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_scanner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanRequest.ProtoReflect.Descriptor instead.
func (*GetScanRequest) Descriptor() ([]byte, []int) {
	return file_v1_scanner_proto_rawDescGZIP(), []int{2}
}

func (x *GetScanRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetScanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Report *ScanReport `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
}

func (x *GetScanResponse) Reset() {
	*x = GetScanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_scanner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScanResponse) ProtoMessage() {}

func (x *GetScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_scanner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScanResponse.ProtoReflect.Descriptor instead.
func (*GetScanResponse) Descriptor() ([]byte, []int) {
	return file_v1_scanner_proto_rawDescGZIP(), []int{3}
}

func (x *GetScanResponse) GetReport() *ScanReport {
	if x != nil {
		return x.Report
	}
	return nil
}

type GetScansRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Start int32  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End   int32  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Limit string `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *GetScansRequest) Reset() {
	*x = GetScansRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_scanner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScansRequest) ProtoMessage() {}

func (x *GetScansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_scanner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScansRequest.ProtoReflect.Descriptor instead.
func (*GetScansRequest) Descriptor() ([]byte, []int) {
	return file_v1_scanner_proto_rawDescGZIP(), []int{4}
}

func (x *GetScansRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GetScansRequest) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *GetScansRequest) GetLimit() string {
	if x != nil {
		return x.Limit
	}
	return ""
}

type GetScansResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reports []*ScanReport `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
}

func (x *GetScansResponse) Reset() {
	*x = GetScansResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_scanner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetScansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScansResponse) ProtoMessage() {}

func (x *GetScansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_scanner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScansResponse.ProtoReflect.Descriptor instead.
func (*GetScansResponse) Descriptor() ([]byte, []int) {
	return file_v1_scanner_proto_rawDescGZIP(), []int{5}
}

func (x *GetScansResponse) GetReports() []*ScanReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

type ScanReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid            string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Image           string   `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Vulnerabilities []string `protobuf:"bytes,3,rep,name=vulnerabilities,proto3" json:"vulnerabilities,omitempty"`
}

func (x *ScanReport) Reset() {
	*x = ScanReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_scanner_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScanReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanReport) ProtoMessage() {}

func (x *ScanReport) ProtoReflect() protoreflect.Message {
	mi := &file_v1_scanner_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanReport.ProtoReflect.Descriptor instead.
func (*ScanReport) Descriptor() ([]byte, []int) {
	return file_v1_scanner_proto_rawDescGZIP(), []int{6}
}

func (x *ScanReport) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ScanReport) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ScanReport) GetVulnerabilities() []string {
	if x != nil {
		return x.Vulnerabilities
	}
	return nil
}

var File_v1_scanner_proto protoreflect.FileDescriptor

var file_v1_scanner_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x31, 0x2f, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x62,
	0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x61, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x62, 0x6f, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x62, 0x6f, 0x6d, 0x22, 0x2e, 0x0a, 0x0f, 0x41, 0x64,
	0x64, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x0e, 0x47, 0x65,
	0x74, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x22, 0x41, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x72, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x22, 0x4f, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x22, 0x44, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x63, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0x60, 0x0a, 0x0a, 0x53, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x76, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f, 0x76, 0x75, 0x6c,
	0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x32, 0x9c, 0x02, 0x0a,
	0x0e, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5a, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x1a, 0x2e, 0x73, 0x63, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x61, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x22, 0x08, 0x2f, 0x76, 0x31,
	0x2f, 0x73, 0x63, 0x61, 0x6e, 0x3a, 0x04, 0x73, 0x62, 0x6f, 0x6d, 0x12, 0x54, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x1a, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x12, 0x08, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x63, 0x61,
	0x6e, 0x12, 0x58, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x73, 0x12, 0x1b, 0x2e,
	0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63,
	0x61, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x63, 0x61,
	0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x63, 0x61, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b,
	0x12, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x63, 0x61, 0x6e, 0x73, 0x42, 0x98, 0x01, 0x0a, 0x0e,
	0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x42, 0x0c,
	0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2f,
	0x7a, 0x65, 0x6c, 0x2f, 0x73, 0x62, 0x6f, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79,
	0x70, 0x65, 0x2f, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x5f, 0x67, 0x65, 0x6e, 0x2f,
	0x67, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x76, 0x31, 0xa2,
	0x02, 0x03, 0x53, 0x58, 0x58, 0xaa, 0x02, 0x0a, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2e,
	0x56, 0x31, 0xca, 0x02, 0x0a, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5c, 0x56, 0x31, 0xe2,
	0x02, 0x16, 0x53, 0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b, 0x53, 0x63, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_scanner_proto_rawDescOnce sync.Once
	file_v1_scanner_proto_rawDescData = file_v1_scanner_proto_rawDesc
)

func file_v1_scanner_proto_rawDescGZIP() []byte {
	file_v1_scanner_proto_rawDescOnce.Do(func() {
		file_v1_scanner_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_scanner_proto_rawDescData)
	})
	return file_v1_scanner_proto_rawDescData
}

var file_v1_scanner_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_scanner_proto_goTypes = []interface{}{
	(*AddScanRequest)(nil),   // 0: scanner.v1.AddScanRequest
	(*AddScanResponse)(nil),  // 1: scanner.v1.AddScanResponse
	(*GetScanRequest)(nil),   // 2: scanner.v1.GetScanRequest
	(*GetScanResponse)(nil),  // 3: scanner.v1.GetScanResponse
	(*GetScansRequest)(nil),  // 4: scanner.v1.GetScansRequest
	(*GetScansResponse)(nil), // 5: scanner.v1.GetScansResponse
	(*ScanReport)(nil),       // 6: scanner.v1.ScanReport
}
var file_v1_scanner_proto_depIdxs = []int32{
	6, // 0: scanner.v1.GetScanResponse.report:type_name -> scanner.v1.ScanReport
	6, // 1: scanner.v1.GetScansResponse.reports:type_name -> scanner.v1.ScanReport
	0, // 2: scanner.v1.ScannerService.AddScan:input_type -> scanner.v1.AddScanRequest
	2, // 3: scanner.v1.ScannerService.GetScan:input_type -> scanner.v1.GetScanRequest
	4, // 4: scanner.v1.ScannerService.GetScans:input_type -> scanner.v1.GetScansRequest
	1, // 5: scanner.v1.ScannerService.AddScan:output_type -> scanner.v1.AddScanResponse
	3, // 6: scanner.v1.ScannerService.GetScan:output_type -> scanner.v1.GetScanResponse
	5, // 7: scanner.v1.ScannerService.GetScans:output_type -> scanner.v1.GetScansResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_scanner_proto_init() }
func file_v1_scanner_proto_init() {
	if File_v1_scanner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_scanner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_scanner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_scanner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_scanner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_scanner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScansRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_scanner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetScansResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_scanner_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScanReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_scanner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_scanner_proto_goTypes,
		DependencyIndexes: file_v1_scanner_proto_depIdxs,
		MessageInfos:      file_v1_scanner_proto_msgTypes,
	}.Build()
	File_v1_scanner_proto = out.File
	file_v1_scanner_proto_rawDesc = nil
	file_v1_scanner_proto_goTypes = nil
	file_v1_scanner_proto_depIdxs = nil
}
