version: '3'

services:
  clickhouse-1:
    image: clickhouse/clickhouse-server:22.10
    restart: on-failure
    environment:
      CLICKHOUSE_DB: uptrace
      SHARD: shard1
      REPLICA: replica1
      KEEPER_ID: 1
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 1s
      timeout: 1s
      retries: 30
    user: clickhouse
    volumes:
      - ch_data:/var/lib/clickhouse
      - ./config/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./config/clickhouse/cluster.xml:/etc/clickhouse-server/config.d/cluster.xml
      - ./config/clickhouse/keeper.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ./config/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '8123:8123'
      - '9300:9000'
      - '9440:9440'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: uptrace
      POSTGRES_PASSWORD: uptrace
    volumes:
      - 'pg_data:/var/lib/postgresql/data/pgdata'
    ports:
      - '5433:5432'

  otelcol:
    image: otel/opentelemetry-collector-contrib:0.70.0
    restart: on-failure
    volumes:
      - ./config/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - '4317:4317'
      - '4318:4318'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  alertmanager:
    image: prom/alertmanager:v0.24.0
    restart: on-failure
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/config.yml
      - alertmanager_data:/alertmanager
    ports:
      - 9093:9093
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: on-failure
    ports:
      - '1025:1025'
      - '8025:8025'

  vector:
    image: timberio/vector:0.28.X-alpine
    volumes:
      - ./config/vector.toml:/etc/vector/vector.toml:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'

#  keycloak:
#    image: quay.io/keycloak/keycloak:19.0.2
#    restart: on-failure
#    ports:
#      - 8080:8080
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    command: start-dev

  grafana:
    image: grafana/grafana:9.5.3
    restart: on-failure
    volumes:
      - ./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./config/grafana/custom.ini:/etc/grafana/grafana.ini
    ports:
      - '3000:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  ch_data:
  pg_data:
  alertmanager_data:
