// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Scan struct {
	ID                 sql.NullInt32  `json:"id"`
	Uuid               uuid.UUID      `json:"uuid"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	Image              string         `json:"image"`
	ImageTag           string         `json:"image_tag"`
	Status             string         `json:"status"`
	SbomID             sql.NullString `json:"sbom_id"`
	Report             sql.NullString `json:"report"`
	ArtifactID         uuid.NullUUID  `json:"artifact_id"`
	ArtifactName       sql.NullString `json:"artifact_name"`
	ArtifactVersion    sql.NullString `json:"artifact_version"`
	VulnerabilityCount sql.NullInt32  `json:"vulnerability_count"`
	CriticalCount      sql.NullInt32  `json:"critical_count"`
	HighCount          sql.NullInt32  `json:"high_count"`
	MediumCount        sql.NullInt32  `json:"medium_count"`
	LowCount           sql.NullInt32  `json:"low_count"`
	Log                sql.NullString `json:"log"`
}
