// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: v1/registry.proto

package registryv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddSbomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sbom string `protobuf:"bytes,1,opt,name=sbom,proto3" json:"sbom,omitempty"`
}

func (x *AddSbomResponse) Reset() {
	*x = AddSbomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_registry_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSbomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSbomResponse) ProtoMessage() {}

func (x *AddSbomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_registry_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSbomResponse.ProtoReflect.Descriptor instead.
func (*AddSbomResponse) Descriptor() ([]byte, []int) {
	return file_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *AddSbomResponse) GetSbom() string {
	if x != nil {
		return x.Sbom
	}
	return ""
}

type AddSbomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *AddSbomRequest) Reset() {
	*x = AddSbomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_registry_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSbomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSbomRequest) ProtoMessage() {}

func (x *AddSbomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_registry_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSbomRequest.ProtoReflect.Descriptor instead.
func (*AddSbomRequest) Descriptor() ([]byte, []int) {
	return file_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *AddSbomRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type GetSbomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSbomRequest) Reset() {
	*x = GetSbomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_registry_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSbomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSbomRequest) ProtoMessage() {}

func (x *GetSbomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_registry_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSbomRequest.ProtoReflect.Descriptor instead.
func (*GetSbomRequest) Descriptor() ([]byte, []int) {
	return file_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *GetSbomRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetSbomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sbom string `protobuf:"bytes,1,opt,name=sbom,proto3" json:"sbom,omitempty"`
}

func (x *GetSbomResponse) Reset() {
	*x = GetSbomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_registry_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSbomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSbomResponse) ProtoMessage() {}

func (x *GetSbomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_registry_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSbomResponse.ProtoReflect.Descriptor instead.
func (*GetSbomResponse) Descriptor() ([]byte, []int) {
	return file_v1_registry_proto_rawDescGZIP(), []int{3}
}

func (x *GetSbomResponse) GetSbom() string {
	if x != nil {
		return x.Sbom
	}
	return ""
}

type GetSbomListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *GetSbomListRequest) Reset() {
	*x = GetSbomListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_registry_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSbomListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSbomListRequest) ProtoMessage() {}

func (x *GetSbomListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_registry_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSbomListRequest.ProtoReflect.Descriptor instead.
func (*GetSbomListRequest) Descriptor() ([]byte, []int) {
	return file_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *GetSbomListRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type GetSbomListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sboms string `protobuf:"bytes,1,opt,name=sboms,proto3" json:"sboms,omitempty"`
}

func (x *GetSbomListResponse) Reset() {
	*x = GetSbomListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_registry_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSbomListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSbomListResponse) ProtoMessage() {}

func (x *GetSbomListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_registry_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSbomListResponse.ProtoReflect.Descriptor instead.
func (*GetSbomListResponse) Descriptor() ([]byte, []int) {
	return file_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *GetSbomListResponse) GetSboms() string {
	if x != nil {
		return x.Sboms
	}
	return ""
}

var File_v1_registry_proto protoreflect.FileDescriptor

var file_v1_registry_proto_rawDesc = []byte{
	0x0a, 0x11, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x15, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x74, 0x74, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x53, 0x62, 0x6f,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x62, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x62, 0x6f, 0x6d, 0x22, 0x26, 0x0a,
	0x0e, 0x41, 0x64, 0x64, 0x53, 0x62, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53, 0x62, 0x6f, 0x6d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x25, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x62,
	0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x62,
	0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x62, 0x6f, 0x6d, 0x22, 0x2a,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x62, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x53, 0x62, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x62, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x62, 0x6f, 0x6d, 0x73, 0x32, 0xbb, 0x02, 0x0a, 0x0f, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x61, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x53, 0x62, 0x6f, 0x6d, 0x12, 0x1b, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x62, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x62, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x73,
	0x62, 0x6f, 0x6d, 0x2f, 0x61, 0x64, 0x64, 0x3a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x5a,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x62, 0x6f, 0x6d, 0x12, 0x1b, 0x2e, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x62, 0x6f, 0x6d, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72,
	0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x62, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x76,
	0x31, 0x2f, 0x73, 0x62, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x74, 0x12, 0x69, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x53, 0x62, 0x6f, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1f, 0x2e, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x62, 0x6f, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x62, 0x6f, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x62, 0x6f, 0x6d, 0x2f, 0x6c,
	0x69, 0x73, 0x74, 0x30, 0x01, 0x42, 0x9f, 0x01, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x42, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x30, 0x7a, 0x65, 0x6c, 0x2f,
	0x73, 0x62, 0x6f, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x73,
	0x63, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x2f, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x76,
	0x31, 0x3b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x52,
	0x58, 0x58, 0xaa, 0x02, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x56, 0x31,
	0xca, 0x02, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_registry_proto_rawDescOnce sync.Once
	file_v1_registry_proto_rawDescData = file_v1_registry_proto_rawDesc
)

func file_v1_registry_proto_rawDescGZIP() []byte {
	file_v1_registry_proto_rawDescOnce.Do(func() {
		file_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_registry_proto_rawDescData)
	})
	return file_v1_registry_proto_rawDescData
}

var file_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_registry_proto_goTypes = []interface{}{
	(*AddSbomResponse)(nil),     // 0: registry.v1.AddSbomResponse
	(*AddSbomRequest)(nil),      // 1: registry.v1.AddSbomRequest
	(*GetSbomRequest)(nil),      // 2: registry.v1.GetSbomRequest
	(*GetSbomResponse)(nil),     // 3: registry.v1.GetSbomResponse
	(*GetSbomListRequest)(nil),  // 4: registry.v1.GetSbomListRequest
	(*GetSbomListResponse)(nil), // 5: registry.v1.GetSbomListResponse
}
var file_v1_registry_proto_depIdxs = []int32{
	1, // 0: registry.v1.RegistryService.AddSbom:input_type -> registry.v1.AddSbomRequest
	2, // 1: registry.v1.RegistryService.GetSbom:input_type -> registry.v1.GetSbomRequest
	4, // 2: registry.v1.RegistryService.GetSbomList:input_type -> registry.v1.GetSbomListRequest
	0, // 3: registry.v1.RegistryService.AddSbom:output_type -> registry.v1.AddSbomResponse
	3, // 4: registry.v1.RegistryService.GetSbom:output_type -> registry.v1.GetSbomResponse
	5, // 5: registry.v1.RegistryService.GetSbomList:output_type -> registry.v1.GetSbomListResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_registry_proto_init() }
func file_v1_registry_proto_init() {
	if File_v1_registry_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_registry_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSbomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_registry_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSbomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_registry_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSbomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_registry_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSbomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_registry_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSbomListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_registry_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSbomListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_registry_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_registry_proto_goTypes,
		DependencyIndexes: file_v1_registry_proto_depIdxs,
		MessageInfos:      file_v1_registry_proto_msgTypes,
	}.Build()
	File_v1_registry_proto = out.File
	file_v1_registry_proto_rawDesc = nil
	file_v1_registry_proto_goTypes = nil
	file_v1_registry_proto_depIdxs = nil
}
