name: scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
        id: go

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Run tests
        run: task test:scanner
