name: scanner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: scanner
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go 1.20
        uses: actions/setup-go@v2
        with:
          go-version: ^1.20
        id: go

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Install Migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.16.2/migrate.linux-amd64.tar.gz | tar xvz
          mv migrate.linux-amd64 /usr/bin
          which migrate

      - name: Run DB migrations
        run: task migrate:up

      - name: Run tests
        run: task test:scanner
